name: Deploy

on:
  push:
    branches:
      - daily-changes

      jobs:
        deploy:
            runs-on: ubuntu-latest

            steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: SSH and deploy
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}